const test = require('node:test');
const assert = require('node:assert/strict');

const {
  solveProblem,
  VERIFIED_SOLVER_MESSAGE
} = require('../netlify/functions/solve');

function assertVerifiedSolverRejection(result) {
  assert.equal(result.status, 'rejected');
  assert.equal(result.title, 'Unsupported advanced problem');
  assert.equal(result.message, VERIFIED_SOLVER_MESSAGE);
  assert.equal(result.answer, VERIFIED_SOLVER_MESSAGE);

  const visibleResponse = [result.title, result.message].concat(result.steps || []).join(' ');
  assert.doesNotMatch(visibleResponse, /\b(?:r|h|d)\s*(?:=|~|≈)/i);
  assert.doesNotMatch(visibleResponse, /\b\d+(?:\.\d+)?\s*m\b/i);
  assert.doesNotMatch(visibleResponse, /\b(?:width|length|depth|radius|height)\s*(?:=|~|≈)/i);
}

test('directExpressionSolver solves simple arithmetic', function() {
  const result = solveProblem('2+2');

  assert.equal(result.status, 'solved');
  assert.equal(result.solver, 'directExpressionSolver');
  assert.equal(result.expression, '2+2');
  assert.equal(result.answer, '4');
});

test('directExpressionSolver solves parenthesized arithmetic safely', function() {
  const result = solveProblem('(18 * 32 + 11 * 24 - 72 + 96 - 24) / 8');

  assert.equal(result.status, 'solved');
  assert.equal(result.solver, 'directExpressionSolver');
  assert.equal(result.expression, '(18 * 32 + 11 * 24 - 72 + 96 - 24) / 8');
  assert.equal(result.answer, '105');
});

test('supportedWordProblemSolver solves the splice tray pattern', function() {
  const result = solveProblem(
    'A fiber crew installs the same number of splice trays in 7 cabinets. Each cabinet gets 18 trays. Later, 9 trays are removed because they are damaged. The remaining trays are split evenly between 3 service zones. How many trays does each zone get?'
  );

  assert.equal(result.status, 'solved');
  assert.equal(result.solver, 'supportedWordProblemSolver');
  assert.equal(result.expression, '(7 * 18 - 9) / 3');
  assert.equal(result.answer, '39');
});

test('unsupportedAdvancedProblemGate rejects wastewater pond optimization', function() {
  const result = solveProblem(
    'A wastewater treatment plant needs a rectangular holding pond with a fixed volume. The liner cost differs for the bottom and sides. Express total cost as a function of one variable, minimize the cost subject to the volume constraint, use the derivative and second derivative, and report the optimal width, length, depth, and exact form.'
  );

  assertVerifiedSolverRejection(result);
});

test('unsupportedAdvancedProblemGate rejects paraboloid tank optimization', function() {
  const result = solveProblem(
    'A chemical processing plant needs to construct a custom storage tank for a highly corrosive liquid. The tank consists of a right circular cylinder of radius r and height h, topped with a paraboloid of revolution generated by rotating y = kx^2 about the y-axis, where the paraboloid has height d and base radius r. The total volume of the tank must be exactly 18,000 liters. The paraboloid cap must match the cylinder radius at the joint. Express the total cost C as a function of one variable, find the values of r, h, and d that minimize total construction cost, compute the minimum cost in exact form, verify the critical point with the second derivative test, derive the surface area of the paraboloid of revolution, justify a global minimum, and discuss calculus and economic interpretation.'
  );

  assertVerifiedSolverRejection(result);
});
