"""
Math engine — safe SymPy/SciPy execution.

Claude generates Python code using SymPy to model and solve the problem.
We execute it in a restricted namespace so Claude can't do anything harmful.
The result must include a RESULT dict with 'answer', 'steps', and 'verified'.
"""

import ast
import math
import traceback
from typing import Any

import numpy as np
import sympy as sp
from sympy import (
    N, Rational, diff, expand, factor, integrate, log, pi, simplify,
    solve, sqrt, symbols, Eq, oo, exp, sin, cos, tan, asin, acos, atan,
    Matrix, linsolve, nonlinsolve, solveset, S, zoo, nan
)
from scipy.optimize import minimize as scipy_minimize, minimize_scalar


# ── Allowed built-in names (no file/network/OS access) ───────────────────────

SAFE_BUILTINS: dict[str, Any] = {
    'abs': abs, 'round': round, 'range': range, 'len': len,
    'list': list, 'dict': dict, 'tuple': tuple, 'set': set,
    'float': float, 'int': int, 'str': str, 'bool': bool,
    'max': max, 'min': min, 'sum': sum, 'sorted': sorted,
    'enumerate': enumerate, 'zip': zip, 'map': map, 'filter': filter,
    'print': print,  # for debug during dev
    'True': True, 'False': False, 'None': None,
    'ValueError': ValueError, 'TypeError': TypeError,
    'Exception': Exception,
}

# ── Forbidden AST node patterns ───────────────────────────────────────────────

FORBIDDEN_NAMES = {
    'eval', 'exec', 'compile', '__import__', 'open', 'os', 'sys',
    'subprocess', 'shutil', 'pathlib', 'socket', 'requests', 'httpx',
    'importlib', 'builtins', 'globals', 'locals', 'vars', 'dir',
    'getattr', 'setattr', 'delattr', 'object', 'type',
}

ALLOWED_IMPORT_ROOTS = {'sympy', 'scipy', 'numpy', 'math'}


def _check_ast_safety(code: str) -> None:
    """Raises ValueError if the code contains forbidden constructs."""
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        raise ValueError(f"Syntax error in generated code: {e}")

    for node in ast.walk(tree):
        # Block forbidden names
        if isinstance(node, ast.Name) and node.id in FORBIDDEN_NAMES:
            raise ValueError(f"Forbidden name used: {node.id}")
        # Block attribute access to dunder methods
        if isinstance(node, ast.Attribute) and node.attr.startswith('__'):
            raise ValueError(f"Forbidden dunder attribute: {node.attr}")
        # Block imports outside the allowlist
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            names = (
                [alias.name for alias in node.names]
                if isinstance(node, ast.Import)
                else [node.module or '']
            )
            for name in names:
                root = name.split('.')[0]
                if root not in ALLOWED_IMPORT_ROOTS:
                    raise ValueError(f"Forbidden import: {name}")


def _build_namespace() -> dict[str, Any]:
    """Build the restricted execution namespace with math tools pre-loaded."""
    return {
        '__builtins__': SAFE_BUILTINS,
        # SymPy top-level
        'sp': sp,
        'symbols': symbols,
        'solve': solve,
        'solveset': solveset,
        'diff': diff,
        'integrate': integrate,
        'simplify': simplify,
        'expand': expand,
        'factor': factor,
        'N': N,
        'Rational': Rational,
        'Eq': Eq,
        'Matrix': Matrix,
        'linsolve': linsolve,
        'nonlinsolve': nonlinsolve,
        'pi': pi,
        'sqrt': sqrt,
        'exp': exp,
        'log': log,
        'sin': sin, 'cos': cos, 'tan': tan,
        'asin': asin, 'acos': acos, 'atan': atan,
        'oo': oo,
        'S': S,
        # NumPy / SciPy
        'np': np,
        'scipy_minimize': scipy_minimize,
        'minimize_scalar': minimize_scalar,
        # stdlib math
        'math': math,
    }


def execute_sympy_code(code: str) -> dict:
    """
    Safely execute SymPy solver code generated by Claude.

    The code must set a RESULT dict with keys:
      answer   (str)  — human-readable final answer with units
      steps    (list) — 3-5 calculation steps
      verified (bool) — did the solution pass a sanity check?
      raw      (dict) — optional raw numerical values for the caller to verify

    Returns the RESULT dict, or raises on error.
    """
    _check_ast_safety(code)

    namespace = _build_namespace()

    try:
        exec(compile(code, '<solver>', 'exec'), namespace)  # noqa: S102
    except Exception as e:
        raise RuntimeError(f"SymPy execution error: {e}\n{traceback.format_exc()}")

    result = namespace.get('RESULT')
    if result is None:
        raise RuntimeError("Solver code did not set a RESULT variable.")
    if not isinstance(result, dict):
        raise RuntimeError(f"RESULT must be a dict, got {type(result)}")
    if 'answer' not in result or 'steps' not in result:
        raise RuntimeError("RESULT must include 'answer' and 'steps' keys.")

    return result


def verify_optimization(result: dict, volume_expr_str: str | None = None) -> bool:
    """
    Generic verification: check that raw values are finite positive numbers
    and that the 'verified' key is set to True by the solver code itself.

    For specific problem types (e.g. optimization) we do deeper checks.
    """
    if not result.get('verified', False):
        return False

    raw = result.get('raw', {})
    for val in raw.values():
        try:
            f = float(val)
            if not math.isfinite(f) or f < 0:
                return False
        except (TypeError, ValueError):
            pass  # non-numeric raw values are OK

    return True
